### ISSUE TITLE
Why not add it via AltStore?

### ISSUE THREAD

**Issue by EinfachRuwen** [NickBouwhuis/hauk-ios#1]
Hi!
I just wondered why you could not publish your app via the AltStore.
It’s just an idea that just came up in my head :)

Greetings from Germany
Ruwen

**Comment by NickBouwhuis** [comment]
Hi Ruwen,

That idea came to me as well. But even for AppStore PAL distribution, you need your app to be notarized by Apple, which requires the subscription.

I bought the subscription tonight, anyway. And submitted a first version for public TestFlight reviewing.

**Comment by NickBouwhuis** [comment]
It is now on TwstFlight. An AppStore release will follow in the future. 

https://testflight.apple.com/join/1VUJFz4Q
